# Generated by Django 3.2.6 on 2021-08-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
